posixunix.scm: Support flock on Haiku
Without this fix, chicken-install fails on Haiku with:

  Error: (file-lock) locking file failed - No such file or directory: 3

c0fc517bd6 disabled support for flock on Haiku because the build of
CHICKEN would fail on that system due to references to undeclared
constants LOCK_SH, LOCK_EX, LOCK_NB and LOCK_UN.  Those actually
exist, but are declared in posix/sys/file.h, which was not being
included.

Tested on Haiku R1/beta5.

Signed-off-by: felix <felix@call-with-current-continuation.org>