Make delete-file* race-free and avoid segv on #f
delete-file* would cause a segmentation violation when given #f as
argument:

  csi -e '(begin (import (chicken file)) (delete-file* #f))'

  Error: segmentation violation

While at it, avoid TOCTOU issues by applying delete-file without
checking for file existence before.  Handle exceptions in case they
occur, and ignore errno/enoent.

Signed-off-by: felix <felix@call-with-current-continuation.org>